services:
  app:
    container_name: env_monitor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: mysql2
      APP_DEBUG: false
    depends_on:
      - mysql2
  mysql2:
    image: mysql:8.0
    container_name: mysql2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

  
